"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowUpRight, Search, Target } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { EmptyState } from "@/components/ui/empty-state";
import { SearchInput } from "@/components/ui/search-input";
import { Score } from "@/components/ui/score";
import { createOpportunity, listOpportunities, type ApiOpportunity } from "@/lib/api/opportunities";
import { demoOpportunities } from "@/data/demo";
import { PageSkeleton } from "@/components/ui/page-skeleton";
import { Dialog } from "@/components/ui/dialog";
import { useToast } from "@/components/ui/toast";

export function OpportunitiesView() {
  const [query, setQuery] = useState(""); const [opportunities, setOpportunities] = useState<ApiOpportunity[]>([]); const [loading, setLoading] = useState(true); const [createOpen, setCreateOpen] = useState(false); const [companyName, setCompanyName] = useState(""); const [stage, setStage] = useState("New"); const [expectedValue, setExpectedValue] = useState("");
  const { showToast } = useToast();
  useEffect(() => { let cancelled = false; setLoading(true); listOpportunities(query).then((data) => { if (!cancelled) { setOpportunities(data); setLoading(false); } }).catch(() => { if (!cancelled) { setOpportunities(demoOpportunities); setLoading(false); } }); return () => { cancelled = true; }; }, [query]);
  if (loading && !opportunities.length) return <PageSkeleton variant="results" />;
  return <div className="space-y-5">
    <section className="flex flex-wrap items-end justify-between gap-4"><div><div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-primary">Pipeline</div><h1 className="page-title mt-2">Growth opportunities</h1><p className="mt-1 text-sm text-muted">Review accounts with strong fit and move them through the pipeline.</p></div><Button onClick={() => setCreateOpen(true)}><Target className="size-4" />Create opportunity</Button></section>
    <Dialog open={createOpen} onClose={() => setCreateOpen(false)} title="Create opportunity" description="Add an account to your growth pipeline."><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); const name = companyName.trim(); if (!name) return; const input = { stage, expectedValue: Number(expectedValue) || 0, status: "open", score: 70 }; createOpportunity(input).then((created) => { setOpportunities((current) => [created, ...current]); }).catch(() => { setOpportunities((current) => [{ id: `demo-${Date.now()}`, company: name, industry: "New account", location: "—", score: 70, employees: "—", stage, status: "open", expectedValue: Number(expectedValue) || 0 }, ...current]); }); showToast("Opportunity added to pipeline"); setCompanyName(""); setExpectedValue(""); setStage("New"); setCreateOpen(false); }}><label className="block"><span className="mb-2 block text-sm font-medium text-ink">Company name</span><input autoFocus required value={companyName} onChange={(event) => setCompanyName(event.target.value)} placeholder="ABC Fashion" className="h-10 w-full rounded-xl border border-border px-3 text-sm outline-none focus:border-primary/50 focus:ring-2 focus:ring-primary/10" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block"><span className="mb-2 block text-sm font-medium text-ink">Stage</span><select value={stage} onChange={(event) => setStage(event.target.value)} className="h-10 w-full rounded-xl border border-border bg-white px-3 text-sm"><option>New</option><option>Discovery</option><option>Qualified</option><option>Proposal</option></select></label><label className="block"><span className="mb-2 block text-sm font-medium text-ink">Expected value</span><input type="number" min="0" value={expectedValue} onChange={(event) => setExpectedValue(event.target.value)} placeholder="25000" className="h-10 w-full rounded-xl border border-border px-3 text-sm outline-none focus:border-primary/50 focus:ring-2 focus:ring-primary/10" /></label></div><div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={() => setCreateOpen(false)}>Cancel</Button><Button type="submit">Create opportunity</Button></div></form></Dialog>
    <Card className="glass-card p-4"><div className="flex flex-col gap-3 sm:flex-row"><div className="flex-1"><SearchInput value={query} onChange={setQuery} onClear={() => setQuery("")} placeholder="Search companies, industries, or stages…" /></div><Button variant="secondary"><Search className="size-4" />Search</Button></div></Card>
    <Card className="glass-card overflow-hidden">{opportunities.length ? <div className="overflow-x-auto"><table className="min-w-[760px] w-full border-collapse"><thead className="bg-elevated text-left text-[11px] font-semibold uppercase tracking-[0.14em] text-subtle"><tr><th className="table-cell">Company</th><th className="table-cell">Industry</th><th className="table-cell">Stage</th><th className="table-cell">Score</th><th className="table-cell">Status</th><th className="table-cell" /></tr></thead><tbody>{opportunities.map((opportunity) => <tr key={opportunity.id} className="border-t border-border/80 hover:bg-elevated/60"><td className="table-cell"><Link href={`/opportunities/${opportunity.id}`} className="font-semibold text-ink hover:text-primary">{opportunity.company || "Unassigned company"}</Link><div className="text-xs text-muted">{opportunity.location || "—"}</div></td><td className="table-cell text-muted">{opportunity.industry || "—"}</td><td className="table-cell"><Badge className="bg-primary-soft text-primary">{opportunity.stage}</Badge></td><td className="table-cell"><Score value={opportunity.score} compact /></td><td className="table-cell text-muted">{opportunity.status || "open"}</td><td className="table-cell"><Link href={`/opportunities/${opportunity.id}`} aria-label="Open opportunity"><ArrowUpRight className="size-4 text-primary" /></Link></td></tr>)}</tbody></table></div> : <div className="p-5"><EmptyState title="No opportunities yet" body="Create an opportunity or import signals to start building your pipeline." /></div>}</Card>
  </div>;
}
