import { Card } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";

function HeaderSkeleton() {
  return <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div className="space-y-2"><Skeleton className="h-3 w-24" /><Skeleton className="h-8 w-64 max-w-[80vw]" /><Skeleton className="h-4 w-80 max-w-[90vw]" /></div><Skeleton className="h-10 w-32 rounded-xl" /></div>;
}

function CardRows({ count = 4 }: { count?: number }) {
  return <div className="space-y-3">{Array.from({ length: count }, (_, index) => <div key={index} className="flex items-center gap-3 rounded-xl border border-border bg-white p-3"><Skeleton className="size-9 shrink-0 rounded-xl" /><div className="min-w-0 flex-1 space-y-2"><Skeleton className="h-4 w-3/5" /><Skeleton className="h-3 w-2/5" /></div><Skeleton className="h-4 w-14 rounded-full" /></div>)}</div>;
}

function TableSkeleton() {
  return <Card className="glass-card overflow-hidden p-4"><div className="space-y-3">{Array.from({ length: 6 }, (_, index) => <div key={index} className="flex items-center gap-3 border-b border-border/70 pb-3 last:border-0 last:pb-0"><Skeleton className="size-9 shrink-0 rounded-xl" /><div className="min-w-0 flex-1 space-y-2"><Skeleton className="h-4 w-2/5" /><Skeleton className="h-3 w-1/4" /></div><Skeleton className="h-5 w-16 rounded-full" /><Skeleton className="h-4 w-12" /></div>)}</div></Card>;
}

export function PageSkeleton({ variant = "workspace" }: { variant?: "dashboard" | "results" | "detail" | "research" | "workspace" }) {
  if (variant === "dashboard") return <div className="min-w-0 space-y-5" aria-label="Loading dashboard"><HeaderSkeleton /><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5">{Array.from({ length: 5 }, (_, index) => <Card key={index} className="glass-card p-4"><Skeleton className="h-3 w-24" /><Skeleton className="mt-3 h-8 w-20" /><Skeleton className="mt-2 h-3 w-28" /></Card>)}</div><div className="grid gap-5 xl:grid-cols-[1.55fr_.85fr]"><Card className="glass-card p-5"><Skeleton className="h-5 w-44" /><Skeleton className="mt-2 h-4 w-64" /><Skeleton className="mt-5 h-56 w-full rounded-2xl" /></Card><Card className="glass-card p-5"><Skeleton className="h-5 w-32" /><Skeleton className="mt-5 h-40 w-full rounded-2xl" /></Card></div><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><TableSkeleton /><Card className="glass-card p-5"><Skeleton className="h-5 w-32" /><div className="mt-5"><CardRows count={4} /></div></Card></div></div>;
  if (variant === "detail") return <div className="min-w-0 space-y-5" aria-label="Loading details"><Skeleton className="h-4 w-36" /><Card className="glass-card p-5"><div className="flex items-start gap-4"><Skeleton className="size-14 shrink-0 rounded-2xl" /><div className="min-w-0 flex-1 space-y-2"><Skeleton className="h-3 w-24" /><Skeleton className="h-8 w-72 max-w-[70vw]" /><Skeleton className="h-4 w-48" /></div><Skeleton className="h-7 w-20 rounded-full" /></div><div className="mt-6 grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <div key={index} className="rounded-2xl border border-border bg-white p-4"><Skeleton className="h-3 w-20" /><Skeleton className="mt-3 h-7 w-24" /><Skeleton className="mt-2 h-3 w-16" /></div>)}</div></Card><div className="flex gap-5 border-b border-border pb-3"><Skeleton className="h-4 w-20" /><Skeleton className="h-4 w-20" /><Skeleton className="h-4 w-20" /><Skeleton className="h-4 w-20" /></div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><Card className="glass-card p-5"><Skeleton className="h-5 w-40" /><div className="mt-5"><CardRows count={4} /></div></Card><Card className="glass-card p-5"><Skeleton className="h-5 w-32" /><div className="mt-5"><CardRows count={3} /></div></Card></div></div>;
  if (variant === "research") return <div className="min-w-0 space-y-5" aria-label="Loading research"><HeaderSkeleton /><Card className="glass-card p-5"><div className="flex gap-3"><Skeleton className="h-10 flex-1 rounded-xl" /><Skeleton className="h-10 w-32 rounded-xl" /></div><div className="mt-6 grid gap-4 xl:grid-cols-[280px_1fr]"><CardRows count={5} /><CardRows count={4} /></div></Card></div>;
  return <div className="min-w-0 space-y-5" aria-label="Loading content"><HeaderSkeleton /><Card className="glass-card p-4"><div className="flex flex-col gap-3 sm:flex-row"><Skeleton className="h-10 flex-1 rounded-xl" /><Skeleton className="h-10 w-28 rounded-xl" /><Skeleton className="h-10 w-24 rounded-xl" /></div></Card>{variant === "results" ? <TableSkeleton /> : <div className="grid gap-5 lg:grid-cols-2"><Card className="glass-card p-5"><Skeleton className="h-5 w-40" /><div className="mt-5"><CardRows count={5} /></div></Card><Card className="glass-card p-5"><Skeleton className="h-5 w-36" /><div className="mt-5"><CardRows count={5} /></div></Card></div>}</div>;
}
